language: node_js
node_js:
- '9.11.1'
branches:
  only:
  - source
before_install:
- git config --global user.name 'Kun Ran'
- git config --global user.email 'rankun203@gmail.com'
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
after_success:
- git status
- git add .
- "git commit -am 'feat: update website'"
- git push --quiet --force origin source
