language: node_js
node_js:
- '9.11.1'
branches:
  only:
  - source
before_install:
- rm -rf .deploy_git
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
after_success:
- git status
