name: Publish Website

on:
  push:
    branches:
      - source
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.*]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Hexo environment
        run: rm -rf .deploy_git && sed -i "s/REPO_TOKE/${REPO_TOKEN}/" _config.yml
      - name: Install hexo
        run: npm install hexo-cli@4.3.0 -g
      - name: Install dependencies
        run: npm install
      - name: Build
        run: hexo clean && hexo generate
      - name: Deploy
        run: hexo deploy
