name: Publish Website

on:
  push:
    branches:
      - source
  repository_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 10.x
        uses: actions/setup-node@v4
        with:
          node-version: '10.x'
      - name: Install hexo
        run: npm install hexo-cli@4.3.0 -g
      - name: Install dependencies
        run: npm install
      - name: Build
        run: hexo clean && hexo generate
      - name: Deploy to master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
